include:
  - project: 'kinga/stream-forge'
    ref: main
    file: '/.gitlab/ci-templates/Python-Service.gitlab-ci.yml'
  - project: 'kinga/stream-forge'
    ref: main
    file: '/.gitlab/ci-templates/Kubernetes-Deploy.gitlab-ci.yml'

build-gnn-trainer:
  extends: .build_python_service
  variables:
    SERVICE_NAME: gnn-trainer
    SERVICE_PATH: services/gnn-trainer
    CI_REGISTRY_IMAGE: $CI_REGISTRY/kinga/stream-forge/gnn-trainer

update-badge-gnn-trainer:
  extends: .update_badge_python_service
  stage: badges
  needs:
    - build-gnn-trainer
  variables:
    SERVICE_NAME: gnn-trainer
    SERVICE_PATH: services/gnn-trainer

test-gnn-trainer:
  extends: .test_python_service
  variables:
    SERVICE_PATH: services/gnn-trainer
  when: manual

deploy-gnn-trainer:
  extends: .deploy_kubernetes_service
  variables:
    K8S_MANIFEST_PATH: services/gnn-trainer/k8s/deployment.yaml
  when: manual
