# values.yaml for gnn-trainer

isJob: true

image:
  repository: registry.dmz.home/kinga/stream-forge/gnn-trainer
  tag: 1.0.0 # Initial version

env:
  # Common Kafka and ArangoDB variables will be inherited from the base chart
  # Specific variables for gnn-trainer
  - name: GRAPH_COLLECTION_NAME
    value: "prepared_graph_data" # Example, will be set by queue-manager
  - name: MINIO_ENDPOINT
    value: "minio.minio:9000"
  - name: MINIO_ACCESS_KEY
    value: "minio_access_key"
  - name: MINIO_SECRET_KEY
    value: "minio_secret_key"
  - name: MINIO_BUCKET_NAME
    value: "gnn-models"
  - name: MODEL_NAME
    value: "market_gnn_v1"
  - name: EPOCHS
    value: "100"
  - name: LEARNING_RATE
    value: "0.01"
  - name: TELEMETRY_PRODUCER_ID
    value: "gnn-trainer-instance" # Example, will be set by queue-manager

serviceAccount:
  rbac:
    rules:
      # Minimal permissions for a gnn-trainer
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list"]
      - apiGroups: [""]
        resources: ["configmaps", "secrets"]
        verbs: ["get"]
      - apiGroups: ["kafka.strimzi.io"]
        resources: ["kafkatopics", "kafkausers"]
        verbs: ["get", "list"]
