apiVersion: v1
kind: Service
metadata:
  name: ssh-gitlab-service
  namespace: devtools
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.152
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
  selector:
    app: ssh-gitlab-runner
