stages:
  - build
  - test
  - deploy

include:
  - '/services/queue-manager/.gitlab-ci.yml'
  - '/services/loader-api-trades/.gitlab-ci.yml'
  - '/services/loader-api-candles/.gitlab-ci.yml'
  - '/services/arango-connector/.gitlab-ci.yml'
  - '/services/dummy-service/.gitlab-ci.yml'

# Job для сборки базового образа
build-base-image:
  stage: build
  image: gcr.io/kaniko-project/executor:debug
  script:
    - BASE_IMAGE_VERSION=$(cat $CI_PROJECT_DIR/platform/VERSION)
    - /kaniko/executor
      --context $CI_PROJECT_DIR/platform
      --dockerfile Dockerfile.base
      --destination registry.dmz.home/kinga/stream-forge/base:$BASE_IMAGE_VERSION
  rules:
    # Автоматический запуск при изменениях в platform/Dockerfile.base или в директории platform/
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - platform/Dockerfile.base
        - platform/**/*
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - platform/Dockerfile.base
        - platform/**/*
    # Разрешить ручной запуск job'а
    - when: manual
      allow_failure: false # Установите true, если пайплайн должен продолжаться, даже если этот ручной job завершится с ошибкой
