stages:
  - setup
  - build
  - test
  - deploy
  - badges

build-kaniko-plus-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    KANIKO_PLUS_IMAGE: registry.dmz.home/kinga/stream-forge/kaniko-plus:v0.0.1
  script:
    - apk add --no-cache ca-certificates
    - cp platform/ci-images/kaniko-plus/ca.crt /usr/local/share/ca-certificates/ca.crt
    - update-ca-certificates
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.dmz.home
    - docker build -t $KANIKO_PLUS_IMAGE platform/ci-images/kaniko-plus/
    - docker push $KANIKO_PLUS_IMAGE
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - platform/ci-images/kaniko-plus/Dockerfile
        - platform/ci-images/kaniko-plus/ca.crt
    - when: manual

include:
  - '/services/queue-manager/.gitlab-ci.yml'
  - '/services/loader-api-trades/.gitlab-ci.yml'
  - '/services/loader-api-candles/.gitlab-ci.yml'
  - '/services/arango-connector/.gitlab-ci.yml'
  - '/services/dummy-service/.gitlab-ci.yml'
  - '/platform/.gitlab-ci.yml'
  - '/.gitlab/ci-templates/Kubernetes-Deploy.gitlab-ci.yml'