stages:
  - setup
  - test
  - build
  - integration-test
  - deploy
  - badges

include:
  - '/.gitlab/ci-templates/Python-Service.gitlab-ci.yml'
  - '/.gitlab/ci-templates/Kubernetes-Deploy.gitlab-ci.yml'
#  - '/services/arango-candles/.gitlab-ci.yml'
  - '/services/arango-connector/.gitlab-ci.yml'
  - '/services/arango-graph-prep/.gitlab-ci.yml'
  - '/services/arango-orderbook/.gitlab-ci.yml'
  - '/services/arango-trades/.gitlab-ci.yml'
  - '/services/dummy-service/.gitlab-ci.yml'
  - '/services/gnn-trainer/.gitlab-ci.yml'
  - '/services/graph_build/.gitlab-ci.yml'
  - '/services/loader-api-candles/.gitlab-ci.yml'
  - '/services/loader-api-trades/.gitlab-ci.yml'
  - '/services/loader-producer/.gitlab-ci.yml'
  - '/services/loader-ws-candles/.gitlab-ci.yml'
  - '/services/loader-ws-orderbook/.gitlab-ci.yml'
  - '/services/loader-ws-trades/.gitlab-ci.yml'
  - '/services/queue-manager/.gitlab-ci.yml'
  - '/services/visualizer/.gitlab-ci.yml'
  - '/platform/.gitlab-ci.yml'