#New ci/cd
include:
  - project: 'kinga/stream-forge'
    ref: main
    file: '/.gitlab/ci-templates/Python-Service.gitlab-ci.yml'
  - project: 'kinga/stream-forge'
    ref: main
    file: '/.gitlab/ci-templates/Kubernetes-Deploy.gitlab-ci.yml'

test-arango-candles:
  extends: .test_python_service
  variables:
    SERVICE_PATH: services/arango-candles
  when: manual

build-arango-candles:
  extends: .build_python_service
  needs:
    - test-arango-candles
  variables:
    SERVICE_NAME: arango-candles
    SERVICE_PATH: services/arango-candles
    CI_REGISTRY_IMAGE: $CI_REGISTRY/kinga/stream-forge/arango-candles

integration-test-arango-candles:
  extends: .integration_test_python_service
  needs:
    - build-arango-candles
  variables:
    SERVICE_NAME: arango-candles
    SERVICE_PATH: services/arango-candles
  when: manual 

deploy-arango-candles:
  extends: .deploy_kubernetes_service
  needs:
    - integration-test-arango-candles
  variables:
    K8S_MANIFEST_PATH: services/arango-candles/k8s/arango-candles-deployment.yaml

update-badge-arango-candles:
  extends: .update_badge_python_service
  needs:
    - deploy-arango-candles
  variables:
    SERVICE_NAME: arango-candles
    SERVICE_PATH: services/arango-candles