apiVersion: v1
data:
  set_index.lua: |
    function cb_set_index(tag, timestamp, record)
        local t = os.time()
        if timestamp and type(timestamp) == "table" and timestamp[1] > 0 then
            t = timestamp[1]
        end

        local app = record["app"] or "unknown"
        local date = os.date("%Y.%m.%d-%H%M", t)

        record["log_index"] = "external-" .. app .. "-" .. date
        return 1, timestamp, record
    end
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"set_index.lua":"function cb_set_index(tag, timestamp, record)\n    local t = os.time()\n    if timestamp and type(timestamp) == \"table\" and timestamp[1] \u003e 0 then\n        t = timestamp[1]\n    end\n\n    local app = record[\"app\"] or \"unknown\"\n    local date = os.date(\"%Y.%m.%d-%H%M\", t)\n\n    record[\"log_index\"] = \"external-\" .. app .. \"-\" .. date\n    return 1, timestamp, record\nend\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"fluentbit-logtap-lua","namespace":"logging"}}
  creationTimestamp: "2025-05-08T23:38:43Z"
  name: fluentbit-logtap-lua
  namespace: logging
  resourceVersion: "12477031"
  uid: 5d724032-3b0c-4b0a-88ef-af4aee350def
