apiVersion: v1
data:
  app.py: |
    from fluent import sender
    import time
    import random
    import json

    APP_NAME = "my-pod-app"

    logger = sender.FluentSender(
        tag='internal.' + APP_NAME,
        host='fluentbit-tailon-forward.logging.svc.k2m.dmz.home',
        port=24224
    )

    def generate_logs():
        levels = ['INFO', 'WARNING', 'ERROR']
        for i in range(200):
            level = random.choice(levels)
            log_record = {
                'message': f'Test log {i}',
                'level': level,
                'app': APP_NAME,
                'iteration': i
            }
            logger.emit('log', log_record)
            print(f"Sent: {json.dumps(log_record)}")
            time.sleep(1)

    if __name__ == '__main__':
        print("Sending logs to fluentbit-tailon-forward.logging.svc.k2m.dmz.home:24224 ...")
        generate_logs()
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"app.py":"from fluent import sender\nimport time\nimport random\nimport json\n\nAPP_NAME = \"my-pod-app\"\n\nlogger = sender.FluentSender(\n    tag='internal.' + APP_NAME,\n    host='fluentbit-tailon-forward.logging.svc.k2m.dmz.home',\n    port=24224\n)\n\ndef generate_logs():\n    levels = ['INFO', 'WARNING', 'ERROR']\n    for i in range(200):\n        level = random.choice(levels)\n        log_record = {\n            'message': f'Test log {i}',\n            'level': level,\n            'app': APP_NAME,\n            'iteration': i\n        }\n        logger.emit('log', log_record)\n        print(f\"Sent: {json.dumps(log_record)}\")\n        time.sleep(1)\n\nif __name__ == '__main__':\n    print(\"Sending logs to fluentbit-tailon-forward.logging.svc.k2m.dmz.home:24224 ...\")\n    generate_logs()\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"test-logger-script","namespace":"logging"}}
  creationTimestamp: "2025-05-09T00:44:08Z"
  name: test-logger-script
  namespace: logging
  resourceVersion: "12531624"
  uid: f65310ca-47fe-4f54-b960-f934a9c3c0f8
