apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: k3
  namespace: kafka
  annotations:
    strimzi.io/kraft: "enabled"
    strimzi.io/node-pools: "enabled"
spec:
  kafka:
    version: "4.0.0"
    authorization:
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
    config:
      inter.broker.protocol.version: "4.0"
      log.message.format.version: "4.0"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: combined
  namespace: kafka
  labels:
    strimzi.io/cluster: k3
spec:
  replicas: 1
  storage:
    type: persistent-claim
    class: standard-rwo
    size: 2Gi
    deleteClaim: true
  roles:
    - controller
    - broker
  resources:
    requests:
      cpu: "800m"
      memory: "4Gi"
    limits:
      cpu: "2"
      memory: "6Gi"
