apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssh-kinga-home-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/nfs/home/kinga
    server: 192.168.1.4
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssh-kinga-home-pvc
  namespace: devtools
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: ssh-kinga-home-pv
  storageClassName: ""
