.build_python_service:
  stage: build
  image: registry.dmz.home/kinga/stream-forge/kaniko-plus:v0.0.2
  script:
    # Переменные $SERVICE_NAME и $SERVICE_PATH должны быть определены в job'е сервиса
    - SERVICE_VERSION=$(cat $CI_PROJECT_DIR/$SERVICE_PATH/VERSION)
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$VERSION
      --destination $CI_REGISTRY_IMAGE:latest
  after_script:
    - |
      if [ "$CI_JOB_STATUS" == "success" ]; then
        BADGE_COLOR="brightgreen"
        BADGE_TEXT="passing"
      else
        BADGE_COLOR="red"
        BADGE_TEXT="failed"
      fi
      
      git config --global user.email "gitlab-ci@dmz.home"
      git config --global user.name "GitLab CI"
      mkdir -p badges/main
      # Создаем значок статуса
      curl -s "https://img.shields.io/badge/${CI_JOB_NAME}-${BADGE_TEXT}-${BADGE_COLOR}" > "badges/main/${CI_JOB_NAME}.svg"
      git add "badges/main/${CI_JOB_NAME}.svg"
      # Создаем значок версии
      SERVICE_VERSION=$(cat $CI_PROJECT_DIR/$SERVICE_PATH/VERSION)
      curl -s "https://img.shields.io/badge/version-${SERVICE_VERSION}-blue" > "badges/main/version-${SERVICE_NAME}.svg"
      git add "badges/main/version-${SERVICE_NAME}.svg"

      if git diff --staged --quiet; then
        echo "No changes to commit"
      else
        git commit -m "ci: update ${CI_JOB_NAME} and version badges [skip ci]"
        git push https://oauth2:${GIT_PUSH_TOKEN}@gitlab.dmz.home/kinga/stream-forge.git HEAD:main
      fi
  rules:
    - when: manual
      allow_failure: false

.test_python_service:
  stage: test
  image: python:3.10-slim
  script:
    # Переменные $SERVICE_PATH должны быть определены в job'е сервиса
    - pip install -r $CI_PROJECT_DIR/$SERVICE_PATH/requirements.txt
    - pytest $CI_PROJECT_DIR/$SERVICE_PATH/tests/
  after_script:
    - |
      if [ "$CI_JOB_STATUS" == "success" ]; then
        BADGE_COLOR="brightgreen"
        BADGE_TEXT="passing"
      else
        BADGE_COLOR="red"
        BADGE_TEXT="failed"
      fi
      
      git config --global user.email "gitlab-ci@dmz.home"
      git config --global user.name "GitLab CI"
      mkdir -p badges/main
      curl -s "https://img.shields.io/badge/${CI_JOB_NAME}-${BADGE_TEXT}-${BADGE_COLOR}" > "badges/main/${CI_JOB_NAME}.svg"
      git add "badges/main/${CI_JOB_NAME}.svg"
      if git diff --staged --quiet; then
        echo "No changes to commit"
      else
        git commit -m "ci: update ${CI_JOB_NAME} badge to ${BADGE_TEXT} [skip ci]"
        git push https://oauth2:${GIT_PUSH_TOKEN}@gitlab.dmz.home/kinga/stream-forge.git HEAD:main
      fi
  rules:
    - when: manual
      allow_failure: false