.build_python_service:
  stage: build
  image: ${KANIKO_IMAGE}
  script:
    - SERVICE_VERSION=$(cat $CI_PROJECT_DIR/$SERVICE_PATH/VERSION)
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR/$SERVICE_PATH
      --dockerfile $CI_PROJECT_DIR/$SERVICE_PATH/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$SERVICE_VERSION
      --destination $CI_REGISTRY_IMAGE:latest
  artifacts:
    paths:
      - $SERVICE_PATH/VERSION
    expire_in: 1 hour

.update_badge_python_service:
  stage: badges
  image: alpine:3.18
  before_script:
    - apk add --no-cache git curl
    - git config --global user.email "gitlab-ci@dmz.home"
    - git config --global user.name "GitLab CI"
  script:
    - |
      echo "Updating badges for ${SERVICE_NAME}..."
      BADGE_COLOR="brightgreen"
      BADGE_TEXT="passing"
      mkdir -p badges/main
      curl -s "https://img.shields.io/badge/build-${SERVICE_NAME}-${BADGE_TEXT}-${BADGE_COLOR}" > "badges/main/build-${SERVICE_NAME}.svg"
      git add "badges/main/build-${SERVICE_NAME}.svg"
      SERVICE_VERSION=$(cat $SERVICE_PATH/VERSION)
      curl -s "https://img.shields.io/badge/version-${SERVICE_VERSION}-blue" > "badges/main/version-${SERVICE_NAME}.svg"
      git add "badges/main/version-${SERVICE_NAME}.svg"
      if git diff --staged --quiet; then
        echo "No changes to badge files to commit for ${SERVICE_NAME}."
      else
        git commit -m "ci: update ${SERVICE_NAME} badges [skip ci]"
        git push https://oauth2:${GIT_PUSH_TOKEN}@gitlab.dmz.home/kinga/stream-forge.git HEAD:main
      fi

.test_python_service:
  stage: test
  image: python:3.10-slim
  script:
    - pip install -r $CI_PROJECT_DIR/$SERVICE_PATH/requirements.txt
    - pytest $CI_PROJECT_DIR/$SERVICE_PATH/tests/