.build_python_service:
  stage: build
  image: gcr.io/kaniko-project/executor:debug
  script:
    # Переменные $SERVICE_NAME и $SERVICE_PATH должны быть определены в job'е сервиса
    - SERVICE_VERSION=$(cat $CI_PROJECT_DIR/$SERVICE_PATH/VERSION)
    - /kaniko/executor
      --context $CI_PROJECT_DIR/$SERVICE_PATH
      --dockerfile Dockerfile
      --destination $CI_REGISTRY_IMAGE/$SERVICE_NAME:$SERVICE_VERSION
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - $SERVICE_PATH/**/*
        - libs/**/* # Пересобирать сервис, если изменилась общая библиотека
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - $SERVICE_PATH/**/*
        - libs/**/*
    - when: manual # Добавляет кнопку "Play" в UI для этого job'а
      allow_failure: false
