.build_python_service:
  stage: build
  image: gcr.io/kaniko-project/executor:debug
  script:
    # Переменные $SERVICE_NAME и $SERVICE_PATH должны быть определены в job'е сервиса
    - SERVICE_VERSION=$(cat $CI_PROJECT_DIR/$SERVICE_PATH/VERSION)
    - /kaniko/executor
      --context $CI_PROJECT_DIR/$SERVICE_PATH
      --dockerfile Dockerfile
      --destination $CI_REGISTRY_IMAGE/$SERVICE_NAME:$SERVICE_VERSION
  rules:
    - when: manual
      allow_failure: false

.test_python_service:
  stage: test
  image: python:3.10-slim
  script:
    # Переменные $SERVICE_PATH должны быть определены в job'е сервиса
    - pip install -r $CI_PROJECT_DIR/$SERVICE_PATH/requirements.txt
    - pytest $CI_PROJECT_DIR/$SERVICE_PATH/tests/
  rules:
    - when: manual
      allow_failure: false
