include:
  - project: 'kinga/stream-forge'
    ref: main
    file: '/.gitlab/ci-templates/Python-Service.gitlab-ci.yml'

build-arango-connector:
  extends: .build_python_service
  variables:
    SERVICE_NAME: arango-connector
    SERVICE_PATH: services/arango-connector
