FROM python:3.11-slim

# Устанавливаем общие системные зависимости, если они нужны
# RUN apt-get update && apt-get install -y ...

# Устанавливаем общие Python-зависимости
RUN pip install uvloop loguru aiokafka

# Копируем и устанавливаем нашу общую библиотеку
COPY ./libs/streamforge_utils /app/libs/streamforge_utils
RUN pip install -e /app/libs/streamforge_utils

WORKDIR /app
