apiVersion: v1
kind: Service
metadata:
  name: ssh-runner-lb
  namespace: devtools
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.152
  selector:
    app: ssh-runner
  ports:
    - name: ssh
      port: 22
      targetPort: 22
