# values.yaml for arango-trades

isJob: true

image:
  repository: registry.dmz.home/kinga/stream-forge/arango-trades
  tag: 1.0.0 # Initial version

env:
  # Common Kafka and ArangoDB variables will be inherited from the base chart
  # Specific variables for arango-trades
  - name: COLLECTION_NAME
    value: "trade_data_2024_08_01" # Example, will be set by queue-manager
  - name: KAFKA_TOPIC
    value: "trade-raw-data" # Example, will be set by queue-manager
  - name: TELEMETRY_PRODUCER_ID
    value: "arango-trades-instance" # Example, will be set by queue-manager

serviceAccount:
  rbac:
    rules:
      # Minimal permissions for an arango-trades
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list"]
      - apiGroups: [""]
        resources: ["configmaps", "secrets"]
        verbs: ["get"]
      - apiGroups: ["kafka.strimzi.io"]
        resources: ["kafkatopics", "kafkausers"]
        verbs: ["get", "list"]
