include:
  - project: 'kinga/stream-forge'
    ref: main
    file: '/.gitlab/ci-templates/Python-Service.gitlab-ci.yml'
  - project: 'kinga/stream-forge'
    ref: main
    file: '/.gitlab/ci-templates/Kubernetes-Deploy.gitlab-ci.yml'

build-queue-manager:
  extends: .build_python_service
  variables:
    SERVICE_NAME: queue-manager
    SERVICE_PATH: services/queue-manager
    CI_REGISTRY_IMAGE: $CI_REGISTRY/kinga/stream-forge/queue-manager

update-badge-queue-manager:
  extends: .update_badge_python_service
  needs:
    - build-queue-manager
  variables:
    SERVICE_NAME: queue-manager
    SERVICE_PATH: services/queue-manager

test-queue-manager:
  extends: .test_python_service
  variables:
    SERVICE_PATH: services/queue-manager
  when: manual
