apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: queue-control
  namespace: {{NAMESPACE}}
  labels:
    strimzi.io/cluster: {{KAFKA_NAME}}
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: "604800000"   # 7d
    segment.bytes: "1073741824" # 1 GiB
    min.insync.replicas: 2
    cleanup.policy: "delete"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: queue-events
  namespace: {{NAMESPACE}}
  labels:
    strimzi.io/cluster: {{KAFKA_NAME}}
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: "604800000"   # 7d
    segment.bytes: "1073741824" # 1 GiB
    min.insync.replicas: 2
    cleanup.policy: "delete"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: user-streamforge
  namespace: {{NAMESPACE}}
  labels:
    strimzi.io/cluster: {{KAFKA_NAME}}
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operation: All
        host: "*"
      - resource:
          type: group
          name: "*"
          patternType: literal
        operation: All
        host: "*"