apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: queue-control
  namespace: kafka
  labels:
    strimzi.io/cluster: k3
spec:
  partitions: 1
  replicas: 3
  config:
    cleanup.policy: delete
    retention.ms: 86400000
