apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: user-streamforge
  namespace: kafka
  labels:
    strimzi.io/cluster: k3
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Read and write to all topics
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operation: Write

      # Allow topic creation (if auto.create.topics.enable=true is used)
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operation: Create

      # Read all consumer groups
      - resource:
          type: group
          name: "*"
          patternType: literal
        operation: Read

