USER-SUPPLIED VALUES:
elasticsearch:
  createIndexTemplate: true
  ilmPolicy:
    deleteAfter: 30d
    maxSize: 2gb
    name: log-retention-30d
    rolloverAfter: 1d
  image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
  ingressHost: elasticsearch
  replicas: 1
  servicePort: 9200
  storageClass: nfs-client
  storageSize: 10Gi
  tlsSecret: elasticsearch-tls
fluentbit:
  elasticsearch:
    host: elasticsearch
    indexPrefix: ${kubernetes['labels']['app']}
    port: 9200
  enableHttpInput: true
  httpInput:
    port: 8888
    tag: external.*
  image: fluent/fluent-bit:4.0.0-amd64
  inputs:
  - name: tail
    parser: syslog
    path: /var/log/syslog
    tag: syslog.*
  - name: tail
    parser: nginx
    path: /var/log/nginx/access.log
    tag: nginx.*
  - name: tail
    parser: syslog
    path: /var/log/auth.log
    tag: auth.*
  lua:
    enabled: true
    script: |
      function filter_log(tag, ts, record)
          if record["app"] ~= nil then
              record["kubernetes"] = record["kubernetes"] or {}
              record["kubernetes"]["labels"] = record["kubernetes"]["labels"] or {}
              record["kubernetes"]["labels"]["app"] = record["app"]
          end
          return 1, record
      end
  serviceMonitor:
    enabled: true
global:
  clusterIssuer: homelab-ca-issuer
  domain: dmz.home
kibana:
  image: docker.elastic.co/kibana/kibana:8.12.0
  ingressHost: kibana
  replicas: 1
  servicePort: 5601
  tlsSecret: kibana-tls
namespace: logging
