apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: devcont0
  namespace: devtools
spec:
  serviceName: devcont-inst1-service
  replicas: 1
  selector:
    matchLabels:
      app: devcont0
  template:
    metadata:
      labels:
        app: devcont0
    spec:
      nodeName: k2w-a
      serviceAccountName: full-access-sa
      enableServiceLinks: true
      containers:
        - name: ssh-container
          image: registry.dmz.home/lib/k8s/devcontainer/dev_kinga:v0.0.14
          imagePullPolicy: Always
          ports:
            - containerPort: 22
          env:
            - name: USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: ssh-pilgrim-config
                  key: USER_NAME
            - name: USER_ID
              valueFrom:
                configMapKeyRef:
                  name: ssh-user-config
                  key: USER_ID
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ssh-user-secret
                  key: USER_PASSWORD
            - name: SSH_AUTHORIZED_KEYS
              valueFrom:
                secretKeyRef:
                  name: ssh-user-secret
                  key: ssh_authorized_keys
          volumeMounts:
            - name: kinga-home
              mountPath: /home/kinga
            - name: ca-certs
              mountPath: /usr/local/share/ca-certificates/dev-ca.crt
              subPath: dev-ca.crt
              readOnly: true
            - name: tensorboard-pvc
              mountPath: /data/nfs/tensorboard-logs
            - name: venv-pv
              mountPath: /data/nfs/venv
        - name: ssh-runner
          image: registry.dmz.home/lib/k8s/devcontainer/gitlab-runner:ubuntu-bleeding-ca
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 999
            runAsGroup: 999
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Запуск GitLab Runner sidecar...";
              gitlab-runner run \
                --working-directory /home/gitlab-runner \
                --config /home/gitlab-runner/config.toml
          volumeMounts:
            - name: runner-home
              mountPath: /home/gitlab-runner
            - name: ca-certs
              mountPath: /usr/local/share/ca-certificates/dev-ca.crt
              subPath: dev-ca.crt
              readOnly: true
      volumes:
        - name: kinga-home
          persistentVolumeClaim:
            claimName: ssh-kinga-home-pvc-inst1
        - name: runner-home
          persistentVolumeClaim:
            claimName: ssh-runner-home-pvc-inst1
        - name: ca-certs
          configMap:
            name: dev-ca-config
