include:
  - project: 'kinga/stream-forge'
    ref: main
    file: '/.gitlab/ci-templates/Python-Service.gitlab-ci.yml'
  - project: 'kinga/stream-forge'
    ref: main
    file: '/.gitlab/ci-templates/Kubernetes-Deploy.gitlab-ci.yml'

build-loader-api-trades:
  extends: .build_python_service
  variables:
    SERVICE_NAME: loader-api-trades
    SERVICE_PATH: services/loader-api-trades
    CI_REGISTRY_IMAGE: $CI_REGISTRY/kinga/stream-forge/loader-api-trades

update-badge-loader-api-trades:
  extends: .update_badge_python_service
  needs:
    - build-loader-api-trades
  variables:
    SERVICE_NAME: loader-api-trades
    SERVICE_PATH: services/loader-api-trades

test-loader-api-trades:
  extends: .test_python_service
  variables:
    SERVICE_PATH: services/loader-api-trades
  when: manual