apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rb
  namespace: stf
subjects:
- kind: ServiceAccount
  name: app-sa
  namespace: stf
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io
