apiVersion: v1
kind: Service
metadata:
  name: __SERVICE_NAME__
  namespace: stf
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: __SERVICE_NAME__
  ports:
  - port: 80
    targetPort: 8000
