apiVersion: v1
kind: ConfigMap
metadata:
  name: queue-manager-config
  namespace: stf
data:
  DEBUG: "true"

  ARANGO_URL: http://abase-1.dmz.home:8529
  ARANGO_DB: streamforge
  ARANGO_USER: root

  K8S_NAMESPACE: stf

  KAFKA_BOOTSTRAP_SERVERS: k3-kafka-bootstrap.kafka:9093
  KAFKA_CLUSTER_NAME: k3
  KAFKA_NAMESPACE: kafka

  KAFKA_USER_PRODUSER: user-streamforge
  KAFKA_USER_CONSUMER: user-streamforge
  QUEUE_EVENTS_TOPIC: queue-events
  QUEUE_CONTROL_TOPIC: queue-control

  CA_PATH: /usr/local/share/ca-certificates/ca.crt

  LOADER_IMAGE: registry.dmz.home/streamforge/loader-producer:v2.0.0
  ARANGO_CONNECTOR_IMAGE: registry.dmz.home/streamforge/arango-connector:v2.0.0
