name: Build Dummy Service

on:
  push:
    paths:
      - 'services/dummy-service/**'
      - '.github/workflows/build-dummy-service.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.BASE_IMAGE }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    permissions:
      contents: read
      packages: write

    env:
      BASE_IMAGE: ${{ vars.BASE_IMAGE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read version from file
        id: get_version
        run: echo "version=$(cat services/dummy-service/VERSION)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: services/dummy-service
          file: services/dummy-service/Dockerfile
          push: true
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/stream-forge-dummy-service:${{ steps.get_version.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/stream-forge-dummy-service:latest
