name: Build & Push Dummy Service

on:
  workflow_dispatch:
  push:
    paths:
      - 'services/dummy-service/**'
      - '.github/workflows/build-dummy-service.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read version from file
        id: read_version
        run: |
          VERSION=$(cat services/dummy-service/VERSION)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Version read: ${VERSION}"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: services/dummy-service
          file: services/dummy-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/stream-forge-dummy-service:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/stream-forge-dummy-service:latest

