name: Build & Push Dummy Service

# Triggers the workflow on push to main or manual dispatch
on:
  workflow_dispatch:  # Manual trigger from GitHub UI
  push:
    branches: [main]
    paths:
      - 'services/dummy-service/**'
      - '.github/workflows/build-dummy-service.yml'
      - 'platform/VERSION'

env:
  VERSION: v0.1.3  # Base image version tag
  BASE_IMAGE: ghcr.io/0leh-kondratov/stream-forge-base:${{ env.VERSION }}
  IMAGE_NAME: ghcr.io/0leh-kondratov/stream-forge-dummy-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner

    permissions:
      contents: read
      packages: write  # Required to push to GHCR

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: services/dummy-service
          file: services/dummy-service/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.IMAGE_NAME }}:latest
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
