name: dummy-service — test & build (manual ready)

on:
  push:
    branches: [ main ]
    paths:
      - "services/dummy-service/**"
      - ".github/workflows/dummy-service-ci.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "services/dummy-service/**"
      - ".github/workflows/dummy-service-ci.yml"
  # Manual trigger from GitHub UI / CLI / API
  workflow_dispatch:
    inputs:
      run_tests_only:
        description: "Skip build and only run tests?"
        required: false
        type: boolean
        default: false
      extra_tag:
        description: "Optional tag to push in addition to VERSION/branch/sha (e.g. 'rc' or 'staging')"
        required: false
        type: string
        default: ""

permissions:
  contents: read   # checkout
  packages: write  # read base image & push built image to GHCR

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: 0leh-kondratov/dummy-service
  SERVICE_DIR: services/dummy-service

jobs:
  tests:
    name: Unit tests (in BASE_IMAGE)
    runs-on: ubuntu-latest
    # Run all steps inside your private base image (GHCR)
    container:
      image: ghcr.io/0leh-kondratov/stream-forge-base:v0.1.3
      # GHCR auth using the automatic GITHUB_TOKEN
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    defaults:
      run:
        working-directory: ${{ env.SERVICE_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show runtime
        run: |
          echo "Runner: $RUNNER_OS"
          python --version
          pip --version
          docker version || true

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles(format('{0}/requirements*.txt', env.SERVICE_DIR)) }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install test deps
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-asyncio httpx

      - name: Run pytest
        run: pytest -q tests

  build:
    name: Build & Push image (GHCR)
    needs: tests
    runs-on: ubuntu-latest
    # If manual run asked "tests only", skip this job.
    if: ${{ !fromJson(github.event.inputs.run_tests_only || 'false') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read VERSION
        id: ver
        run: |
          echo "version=$(cat ${SERVICE_DIR}/VERSION)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.IMAGE_REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Docker metadata (tags & labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # version from file
            type=raw,value=${{ steps.ver.outputs.version }}
            # git branch tag (e.g., main)
            type=ref,event=branch
            # short sha tag
            type=sha,prefix=sha-,format=short
            # latest only on main
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            # optional extra tag from manual input
            type=raw,value=${{ github.event.inputs.extra_tag }},enable=${{ github.event.inputs.extra_tag != '' }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.ver.outputs.version }}

      - name: Build & Push (dummy-service)
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.SERVICE_DIR }}
          file: ${{ env.SERVICE_DIR }}/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Summary
        run: |
          echo "Pushed tags:"
          echo "${{ steps.meta.outputs.tags }}"
