name: Build and Push Base Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'platform/**'
      - '.github/workflows/build-base-image.yml'

jobs:
  build-base:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read VERSION from file
        id: read-version
        run: |
          VERSION=$(cat platform/VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: platform
          file: platform/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/stream-forge-base:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/stream-forge-base:latest

