name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
      - develop
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push images to GHCR

    strategy:
      matrix:
        service:
          - arango-candles
          - arango-connector
          - arango-graph-prep
          - arango-orderbook
          - arango-trades
          - dummy-service
          - gnn-trainer
          - graph_build
          - loader-api-candles
          - loader-api-trades
          - loader-producer
          - loader-ws-candles
          - loader-ws-orderbook
          - loader-ws-trades
          - queue-manager
          - visualizer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/streamforge/${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/${{ matrix.service }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
