name: Build & Push Base Image

on:
  workflow_dispatch:
  push:
    paths:
      - "platform/**"
      - ".github/workflows/build-base-image.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    env:
      IMAGE_NAME: ghcr.io/0leh-kondratov/stream-forge-base

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read VERSION file
        id: get_version
        run: |
          echo "VERSION=$(cat platform/VERSION)" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./platform
          file: ./platform/Dockerfile
          push: true
          build-args: |
            BASE_IMAGE=python:3.11-slim
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.IMAGE_NAME }}:latest

